<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet"/>
        <PackageReference Include="Microsoft.Orleans.GrainDirectory.Redis"/>
        <PackageReference Include="Microsoft.Orleans.Reminders.AdoNet"/>
        <PackageReference Include="Microsoft.Orleans.Sdk"/>
        <PackageReference Include="Microsoft.Orleans.TestingHost"/>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="SSH.NET"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
        <PackageReference Include="Testcontainers.RabbitMq"/>
        <PackageReference Include="Testcontainers.Redis"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="coverlet.collector"/>
    </ItemGroup>
    <ItemGroup>
        <None Update="OrleansSql/*.sql">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../../src/Stratara.EventSourcing.WorkerDefaults/Stratara.EventSourcing.WorkerDefaults.csproj"/>
        <ProjectReference Include="../../src/Stratara.Orleans/Stratara.Orleans.csproj"/>
        <ProjectReference Include="../../src/Stratara.Orleans.EntityFrameworkCore/Stratara.Orleans.EntityFrameworkCore.csproj"/>
    </ItemGroup>
</Project>
