using Microsoft.AspNetCore.Authorization;

namespace Stratara.Identity.AspNetCore.Authorization;

/// <summary>
/// ASP.NET Core authorization requirement carrying one Stratara permission name — the policy
/// payload behind <c>[Authorize("sims.read")]</c>-style endpoint gates generated by the
/// permission policy provider.
/// </summary>
/// <param name="permission">The permission the caller must hold.</param>
public sealed class PermissionRequirement(string permission) : IAuthorizationRequirement
{
    /// <summary>The permission the caller must hold.</summary>
    public string Permission { get; } = permission;
}
